channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - configparser
  - graphviz
  - ipykernel
  - pip
  - pandas
  - numpy
  - scipy
  - dask
  - cytoolz
  - python-rapidjson
  - gensim
  - scikit-learn
  - spacy
  - matplotlib=3.4.3
  - seaborn
  - umap-learn
  - pyarrow
  - graphviz
  - pydot
  - xgboost
  - pillow
  - wordcloud
  - numba >= 0.4
  - pytorch
  - graph-tool
  - jupyter
  - geopandas
  - libpysal
  - mapclassify
  - statsmodels
  - networkx
  - spectra
  - descartes
  - scikit-learn
  - jq
  - pip:
    - lru-dict
    - pytz
    - ftfy
    - hdbscan
    - emoji
    - scattertext
    - adjustText
    - toml
    - KDEpy
    - spectra
    - pyahocorasick
    - powerlaw
    - shifterator
    - git+https://github.com/zorzalerrante/aves
    - pymunk
    - emoji
    - git+https://github.com/mims-harvard/scikit-fusion
    - bezier
    - scattertext
    - KDEpy
    - adjustText
    - contextily
    - matplotlib-scalebar
    - xlrd
    - python-dotenv