channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - configparser
  - ipykernel
  - pip
  - pandas
  - numpy
  - scipy
  - dask
  - cytoolz
  - python-rapidjson
  - gensim
  - scikit-learn
  - matplotlib=3.4.3
  - seaborn
  - umap-learn
  - pyarrow
  - graphviz
  - pydot
  - xgboost
  - pillow
  - wordcloud
  - graph-tool
  - jupyter
  - statsmodels
  - networkx
  - spectra
  - nltk
  - pip:
    - lru-dict
    - pytz
    - ftfy
    - emoji
    - scattertext
    - adjustText
    - toml
    - powerlaw
    - shifterator
    - git+https://github.com/zorzalerrante/scikit-fusion
    - git+https://github.com/zorzalerrante/aves
    - pymunk
    - emoji
    - bezier
    - scattertext
    - adjustText
    - xlrd
    - python-dotenv
    - tweepy
    - requests
    - aiohttp