[experiments]

[experiments.test]
key = 'test'
folder_pattern = '*'
folder_start = '2022-01-27'
folder_end = '2022-01-28'
# folder_end = '2022-03-31'
discussion_only = 1
discussion_directed = 0

[experiments.test.topic_modeling]
n_topics = 200
min_tweets = 10
max_tweets_quantile = 0.98
min_users = 1000
max_users_quantile = 0.98
n_jobs = 2
passes = 2
alpha = 'asymmetric'


[thresholds]
name_tokens = 50
description_tokens = 50
tweet_tokens = 50
tweet_domains = 50
profile_domains = 30
profile_tlds = 50
edge_weight = 3

[relevance]

[relevance.xgb]
learning_rate = 0.125
max_depth = 2
subsample = 0.75
colsample = 0.75
n_estimators = 300
max_delta_step = 1
n_jobs = 2
seed = 42
objective = 'binary:logistic'

[relevance.pipeline]
early_stopping_rounds = 15
eval_fraction = 0.05
threshold_offset_factor = 0.2


[stance]

[stance.xgb]
learning_rate = 0.15
max_depth = 3
subsample = 1.0
colsample = 1.0
n_estimators = 400
max_delta_step = 1
n_jobs = 2
seed = 42
objective = 'binary:logistic'

[stance.pipeline]
early_stopping_rounds = 10
eval_fraction = 0.1
threshold_offset_factor = 0.05


[person]

[person.xgb]
learning_rate = 0.15
max_depth = 3
subsample = 0.9
colsample = 0.9
n_estimators = 250
max_delta_step = 1
n_jobs = 2
seed = 42
objective = 'multi:softmax'

[person.pipeline]
early_stopping_rounds = 10
eval_fraction = 0.1
threshold_offset_factor = 0.2

[location]

[location.xgb]
learning_rate = 0.15
max_depth = 3
subsample = 1.0
colsample = 1.0
n_estimators = 300
max_delta_step = 1
n_jobs = 2
seed = 42
objective = 'multi:softmax'

[location.pipeline]
early_stopping_rounds = 10
eval_fraction = 0.1
threshold_offset_factor = 0.05
